package com.enterprise.rag.milvus;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import io.milvus.v2.client.MilvusClientV2;
import io.milvus.v2.common.IndexParam;
import io.milvus.v2.service.collection.request.AddFieldReq;
import io.milvus.v2.service.collection.request.CreateCollectionReq;
import io.milvus.v2.service.collection.request.HasCollectionReq;
import io.milvus.v2.service.vector.request.AnnSearchReq;
import io.milvus.v2.service.vector.request.DeleteReq;
import io.milvus.v2.service.vector.request.HybridSearchReq;
import io.milvus.v2.service.vector.request.InsertReq;
import io.milvus.v2.service.vector.request.SearchReq;
import io.milvus.v2.service.vector.request.data.BaseVector;
import io.milvus.v2.service.vector.request.data.EmbeddedText;
import io.milvus.v2.service.vector.request.data.FloatVec;
import io.milvus.v2.service.vector.request.ranker.RRFRanker;
import io.milvus.v2.service.vector.response.SearchResp;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.*;

/**
 * Milvus Dual-Engine Service (v2.5+)
 *
 * Implements hybrid search combining:
 * - Dense vector search (semantic/embedding-based)
 * - Sparse vector search (BM25/keyword-based)
 * - RRF (Reciprocal Rank Fusion) for result fusion
 *
 * Key Features (Milvus 2.5+):
 * - Built-in BM25 function (Doc-in-Doc-out)
 * - Automatic text tokenization and sparse vector generation
 * - Native HybridSearch API support
 *
 * @author Enterprise RAG System
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class MilvusDualEngineService {

    private final MilvusClientV2 milvusClientV2;

    @Qualifier("milvusCollectionName")
    private final String collectionName;

    @Qualifier("milvusEmbeddingDimension")
    private final Integer embeddingDimension;

    @Value("${hybrid-search.dense-top-k:100}")
    private int denseTopK;

    @Value("${hybrid-search.sparse-top-k:100}")
    private int sparseTopK;

    @Value("${hybrid-search.rrf-k:60}")
    private int rrfK;

    @Value("${hybrid-search.final-top-k:10}")
    private int finalTopK;

    // Field names in Milvus collection
    private static final String FIELD_ID = "id";
    private static final String FIELD_CONTENT = "content";
    private static final String FIELD_DENSE_VECTOR = "dense_vector";
    private static final String FIELD_SPARSE_VECTOR = "sparse_vector";
    private static final String FIELD_TENANT_ID = "tenant_id";
    private static final String FIELD_DOC_ID = "doc_id";
    private static final String FIELD_CHUNK_INDEX = "chunk_index";
    private static final String FIELD_METADATA = "metadata";

    // Default search parameters
    private static final int MAX_CONTENT_LENGTH = 65535;

    @PostConstruct
    public void init() {
        log.info("========================================");
        log.info("Initializing Milvus Dual-Engine Service");
        log.info("========================================");
        log.info("Collection Name: {}", collectionName);
        log.info("Embedding Dimension: {}", embeddingDimension);
        log.info("Hybrid Search Config: dense-top-k={}, sparse-top-k={}, rrf-k={}, final-top-k={}",
                denseTopK, sparseTopK, rrfK, finalTopK);

        // Initialize collection
        initializeCollection();
    }

    /**
     * Initialize collection for hybrid search
     *
     * Schema Design:
     * - id: Primary key (auto-generated)
     * - content: Original text with enableAnalyzer=true for BM25
     * - dense_vector: Embedding vector for semantic search
     * - sparse_vector: BM25 sparse vector (auto-generated by function)
     * - tenant_id: Tenant isolation metadata
     * - doc_id: Document ID reference
     * - chunk_index: Chunk sequence number
     * - metadata: Additional metadata (JSON string)
     */
    private void initializeCollection() {
        try {
            boolean exists = milvusClientV2.hasCollection(HasCollectionReq.builder()
                    .collectionName(collectionName)
                    .build());

            if (exists) {
                log.info("Collection '{}' already exists, skipping creation", collectionName);
                return;
            }

            log.info("Creating collection '{}' with dual-engine schema", collectionName);

            // Create schema using the SDK's schema factory method
            CreateCollectionReq.CollectionSchema schema = milvusClientV2.createSchema();

            // Primary key field
            schema.addField(AddFieldReq.builder()
                    .fieldName(FIELD_ID)
                    .dataType(io.milvus.v2.common.DataType.Int64)
                    .isPrimaryKey(true)
                    .autoID(true)
                    .build());

            // Content field with analyzer enabled (for BM25 in Milvus 2.5+)
            schema.addField(AddFieldReq.builder()
                    .fieldName(FIELD_CONTENT)
                    .dataType(io.milvus.v2.common.DataType.VarChar)
                    .maxLength(MAX_CONTENT_LENGTH)
                    .enableAnalyzer(true)
                    .build());

            // Dense vector field
            schema.addField(AddFieldReq.builder()
                    .fieldName(FIELD_DENSE_VECTOR)
                    .dataType(io.milvus.v2.common.DataType.FloatVector)
                    .dimension(embeddingDimension)
                    .build());

            // Sparse vector field (for BM25)
            schema.addField(AddFieldReq.builder()
                    .fieldName(FIELD_SPARSE_VECTOR)
                    .dataType(io.milvus.v2.common.DataType.SparseFloatVector)
                    .build());

            // Tenant ID field
            schema.addField(AddFieldReq.builder()
                    .fieldName(FIELD_TENANT_ID)
                    .dataType(io.milvus.v2.common.DataType.VarChar)
                    .maxLength(256)
                    .build());

            // Document ID field
            schema.addField(AddFieldReq.builder()
                    .fieldName(FIELD_DOC_ID)
                    .dataType(io.milvus.v2.common.DataType.VarChar)
                    .maxLength(256)
                    .build());

            // Chunk index field
            schema.addField(AddFieldReq.builder()
                    .fieldName(FIELD_CHUNK_INDEX)
                    .dataType(io.milvus.v2.common.DataType.Int32)
                    .build());

            // Metadata field
            schema.addField(AddFieldReq.builder()
                    .fieldName(FIELD_METADATA)
                    .dataType(io.milvus.v2.common.DataType.VarChar)
                    .maxLength(4000)
                    .build());

            // Define indexes
            List<IndexParam> indexParams = new ArrayList<>();

            // Dense vector index
            indexParams.add(IndexParam.builder()
                    .fieldName(FIELD_DENSE_VECTOR)
                    .indexType(IndexParam.IndexType.AUTOINDEX)
                    .metricType(IndexParam.MetricType.COSINE)
                    .build());

            // Sparse vector index
            indexParams.add(IndexParam.builder()
                    .fieldName(FIELD_SPARSE_VECTOR)
                    .indexType(IndexParam.IndexType.SPARSE_INVERTED_INDEX)
                    .metricType(IndexParam.MetricType.BM25)
                    .build());

            // Create collection
            milvusClientV2.createCollection(CreateCollectionReq.builder()
                    .collectionName(collectionName)
                    .collectionSchema(schema)
                    .indexParams(indexParams)
                    .build());

            log.info("Collection '{}' created successfully with dual-engine schema", collectionName);

        } catch (Exception e) {
            log.error("Failed to initialize collection: {}", e.getMessage(), e);
            log.warn("Collection initialization failed, will use fallback mode");
        }
    }

    /**
     * Insert document chunk
     *
     * @param content Document chunk text
     * @param denseVector Embedding vector
     * @param tenantId Tenant ID
     * @param docId Document ID
     * @param chunkIndex Chunk sequence number
     * @param metadata Additional metadata
     * @return Inserted primary keys
     */
    public List<Object> insertDocument(String content, float[] denseVector,
                                       String tenantId, String docId,
                                       int chunkIndex, Map<String, Object> metadata) {
        try {
            JsonObject row = new JsonObject();
            row.addProperty(FIELD_CONTENT, content);
            row.addProperty(FIELD_TENANT_ID, tenantId);
            row.addProperty(FIELD_DOC_ID, docId);
            row.addProperty(FIELD_CHUNK_INDEX, chunkIndex);

            if (metadata != null && !metadata.isEmpty()) {
                com.google.gson.Gson gson = new com.google.gson.Gson();
                row.addProperty(FIELD_METADATA, gson.toJson(metadata));
            }

            JsonArray vecArray = new JsonArray();
            for (float v : denseVector) {
                vecArray.add(v);
            }
            row.add(FIELD_DENSE_VECTOR, vecArray);

            var response = milvusClientV2.insert(InsertReq.builder()
                    .collectionName(collectionName)
                    .data(Collections.singletonList(row))
                    .build());

            List<Object> ids = response.getPrimaryKeys();
            log.debug("Inserted: docId={}, chunkIndex={}, pk={}", docId, chunkIndex, ids);

            return ids;

        } catch (Exception e) {
            log.error("Failed to insert document: {}", e.getMessage(), e);
            throw new RuntimeException("Failed to insert document", e);
        }
    }

    /**
     * Batch insert document chunks
     *
     * @param chunks List of document chunks
     * @return List of inserted primary keys
     */
    public List<Object> batchInsert(List<DocumentChunk> chunks) {
        if (chunks == null || chunks.isEmpty()) {
            return Collections.emptyList();
        }

        try {
            List<JsonObject> rows = new ArrayList<>();
            com.google.gson.Gson gson = new com.google.gson.Gson();

            for (DocumentChunk chunk : chunks) {
                JsonObject row = new JsonObject();
                row.addProperty(FIELD_CONTENT, chunk.getContent());
                row.addProperty(FIELD_TENANT_ID, chunk.getTenantId());
                row.addProperty(FIELD_DOC_ID, chunk.getDocId());
                row.addProperty(FIELD_CHUNK_INDEX, chunk.getChunkIndex());

                if (chunk.getMetadata() != null && !chunk.getMetadata().isEmpty()) {
                    row.addProperty(FIELD_METADATA, gson.toJson(chunk.getMetadata()));
                }

                JsonArray vecArray = new JsonArray();
                for (float v : chunk.getDenseVector()) {
                    vecArray.add(v);
                }
                row.add(FIELD_DENSE_VECTOR, vecArray);

                rows.add(row);
            }

            var response = milvusClientV2.insert(InsertReq.builder()
                    .collectionName(collectionName)
                    .data(rows)
                    .build());

            log.info("Batch inserted {} chunks", chunks.size());
            return response.getPrimaryKeys();

        } catch (Exception e) {
            log.error("Failed to batch insert: {}", e.getMessage(), e);
            throw new RuntimeException("Failed to batch insert", e);
        }
    }

    /**
     * Semantic search (dense vector only)
     *
     * @param denseVector Query embedding
     * @param tenantId Tenant ID
     * @param topK Number of results
     * @return Search results
     */
    public List<HybridSearchResult> semanticSearch(float[] denseVector, String tenantId, int topK) {
        try {
            List<Float> denseList = new ArrayList<>(denseVector.length);
            for (float v : denseVector) {
                denseList.add(v);
            }

            SearchReq searchReq = SearchReq.builder()
                    .collectionName(collectionName)
                    .annsField(FIELD_DENSE_VECTOR)
                    .data(Collections.singletonList(new FloatVec(denseList)))
                    .metricType(IndexParam.MetricType.COSINE)
                    .topK(topK)
                    .outputFields(List.of(FIELD_ID, FIELD_CONTENT, FIELD_DOC_ID, FIELD_CHUNK_INDEX, FIELD_TENANT_ID))
                    .filter("tenant_id == \"" + tenantId + "\"")
                    .build();

            SearchResp response = milvusClientV2.search(searchReq);
            return parseSearchResults(response);

        } catch (Exception e) {
            log.error("Semantic search failed: {}", e.getMessage(), e);
            throw new RuntimeException("Semantic search failed", e);
        }
    }

    /**
     * Keyword search (sparse vector BM25)
     *
     * @param queryText Query text
     * @param tenantId Tenant ID
     * @param topK Number of results
     * @return Search results
     */
    public List<HybridSearchResult> keywordSearch(String queryText, String tenantId, int topK) {
        try {
            SearchReq searchReq = SearchReq.builder()
                    .collectionName(collectionName)
                    .annsField(FIELD_SPARSE_VECTOR)
                    .data(Collections.singletonList(new EmbeddedText(queryText)))
                    .metricType(IndexParam.MetricType.BM25)
                    .topK(topK)
                    .outputFields(List.of(FIELD_ID, FIELD_CONTENT, FIELD_DOC_ID, FIELD_CHUNK_INDEX, FIELD_TENANT_ID))
                    .filter("tenant_id == \"" + tenantId + "\"")
                    .build();

            SearchResp response = milvusClientV2.search(searchReq);
            return parseSearchResults(response);

        } catch (Exception e) {
            log.error("Keyword search failed: {}", e.getMessage(), e);
            throw new RuntimeException("Keyword search failed", e);
        }
    }

    /**
     * Hybrid search with RRF fusion
     *
     * @param queryText Query text
     * @param denseVector Query embedding
     * @param tenantId Tenant ID
     * @param topK Number of final results
     * @return Fused search results
     */
    public List<HybridSearchResult> hybridSearch(String queryText, float[] denseVector,
                                                  String tenantId, int topK) {
        try {
            // Dense search request
            List<Float> denseList = new ArrayList<>(denseVector.length);
            for (float v : denseVector) {
                denseList.add(v);
            }

            AnnSearchReq denseReq = AnnSearchReq.builder()
                    .vectorFieldName(FIELD_DENSE_VECTOR)
                    .vectors(Collections.singletonList(new FloatVec(denseList)))
                    .metricType(IndexParam.MetricType.COSINE)
                    .topK(denseTopK)
                    .expr("tenant_id == \"" + tenantId + "\"")
                    .build();

            // Sparse search request (BM25)
            AnnSearchReq sparseReq = AnnSearchReq.builder()
                    .vectorFieldName(FIELD_SPARSE_VECTOR)
                    .vectors(Collections.singletonList(new EmbeddedText(queryText)))
                    .metricType(IndexParam.MetricType.BM25)
                    .topK(sparseTopK)
                    .expr("tenant_id == \"" + tenantId + "\"")
                    .build();

            // RRF fusion
            HybridSearchReq hybridReq = HybridSearchReq.builder()
                    .collectionName(collectionName)
                    .searchRequests(List.of(denseReq, sparseReq))
                    .ranker(new RRFRanker(rrfK))
                    .topK(topK > 0 ? topK : finalTopK)
                    .outFields(List.of(FIELD_ID, FIELD_CONTENT, FIELD_DOC_ID, FIELD_CHUNK_INDEX, FIELD_TENANT_ID))
                    .build();

            SearchResp response = milvusClientV2.hybridSearch(hybridReq);
            return parseSearchResults(response);

        } catch (Exception e) {
            log.error("Hybrid search failed: {}", e.getMessage(), e);
            // Fallback to semantic search
            log.warn("Hybrid search failed, falling back to semantic search");
            return semanticSearch(denseVector, tenantId, topK);
        }
    }

    /**
     * Parse search results from response
     */
    private List<HybridSearchResult> parseSearchResults(SearchResp response) {
        if (response.getSearchResults() == null || response.getSearchResults().isEmpty()) {
            return Collections.emptyList();
        }

        List<HybridSearchResult> results = new ArrayList<>();
        for (SearchResp.SearchResult sr : response.getSearchResults().get(0)) {
            Map<String, Object> fields = sr.getEntity();
            results.add(HybridSearchResult.builder()
                    .id(String.valueOf(fields.get(FIELD_ID)))
                    .content(String.valueOf(fields.get(FIELD_CONTENT)))
                    .docId(String.valueOf(fields.get(FIELD_DOC_ID)))
                    .chunkIndex(((Number) fields.get(FIELD_CHUNK_INDEX)).intValue())
                    .tenantId(String.valueOf(fields.get(FIELD_TENANT_ID)))
                    .score(sr.getScore())
                    .build());
        }
        return results;
    }

    /**
     * Delete documents by docId
     */
    public void deleteByDocId(String docId, String tenantId) {
        try {
            String filter = "doc_id == \"" + docId + "\" && tenant_id == \"" + tenantId + "\"";

            milvusClientV2.delete(DeleteReq.builder()
                    .collectionName(collectionName)
                    .filter(filter)
                    .build());

            log.info("Deleted documents: docId={}, tenant={}", docId, tenantId);

        } catch (Exception e) {
            log.error("Failed to delete documents: {}", e.getMessage(), e);
            throw new RuntimeException("Failed to delete documents", e);
        }
    }

    /**
     * Health check
     */
    public boolean isHealthy() {
        try {
            return milvusClientV2.hasCollection(HasCollectionReq.builder()
                    .collectionName(collectionName)
                    .build());
        } catch (Exception e) {
            log.error("Health check failed: {}", e.getMessage());
            return false;
        }
    }

    // ==================== Inner Classes ====================

    @lombok.Data
    @lombok.Builder
    public static class DocumentChunk {
        private String content;
        private float[] denseVector;
        private String tenantId;
        private String docId;
        private int chunkIndex;
        private Map<String, Object> metadata;
    }

    @lombok.Data
    @lombok.Builder
    public static class HybridSearchResult {
        private String id;
        private String content;
        private String docId;
        private int chunkIndex;
        private String tenantId;
        private float score;
        private Map<String, Object> metadata;
    }
}
